# https://github.com/golangci/golangci-lint-action
---
name: golangci-lint
on: [push]

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57
          working-directory: ./mathfunctions
      - name: run lint
        working-directory: ./mathfunctions
        run: |
          ls -a
          golangci-lint run "$(ls --directory */)" --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Install dependencies
        working-directory: ./mathfunctions
        run: go get .
      - name: Test with the Go CLI
        working-directory: ./mathfunctions/bhaskara
        run: go test
